# Generated by Django 6.0.1 on 2026-01-15 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_lote', models.CharField(max_length=50)),
                ('fecha_vencimiento', models.DateField()),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('cantidad_inicial', models.PositiveIntegerField()),
                ('cantidad_actual', models.PositiveIntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='inventario.producto')),
            ],
            options={
                'ordering': ['fecha_vencimiento'],
            },
        ),
    ]
